kind: Configuration
apiVersion: dapr.io/v1alpha1
metadata:
  name: dapr-playground-config
  namespace: dapr-playground
spec:
  tracing:
    samplingRate: "1"
    zipkin:
      endpointAddress: http://localhost:9411/api/v2/spans
  metric:
    enabled: true