apiVersion: apps/v1
kind: Deployment
metadata:
  name: subject-binding
  namespace: dapr-playground
  labels:
    app: subject-binding
spec:
  selector:
    matchLabels:
      app : subject-binding
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: subject-binding
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "subject-binding"
        dapr.io/app-port: "80"
        dapr.io/enable-profiling: "false"
        dapr.io/config: "dapr-playground-config"
    spec:
      containers:
        - name: subject-binding
          image: nunofilipecosta/subjectbinding:dev
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: subject-binding-service
  namespace: dapr-playground
  labels: 
    app: subject-binding
spec:
  type: NodePort
  selector:
    app: subject-binding
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP

