apiVersion: apps/v1
kind: Deployment
metadata:
  name: topic-listener
  namespace: dapr-playground
  labels:
    app: topic-listener
spec:
  selector:
    matchLabels:
      app : topic-listener
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: topic-listener
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "topic-listener"
        dapr.io/app-port: "80"
        dapr.io/enable-profiling: "false"
        dapr.io/config: "dapr-playground-config"
    spec:
      containers:
        - name: topic-listener
          image: nunofilipecosta/topiclistener:dev
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: topic-listener-service
  namespace: dapr-playground
  labels: 
    app: topic-listener
spec:
  type: NodePort
  selector:
    app: topic-listener
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP

--- 
apiVersion: dapr.io/v1alpha1
kind: Subscription
metadata:
  name: topicsubscription
  namespace: dapr-playground
spec:
  topic: tq-city-inspector-eh-location-events-dev
  route: /receiver
  pubsubname: topicpubsub
scopes:
 - topic-listener
