apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: topicpubsub
  namespace: dapr-playground
spec:
  type: pubsub.azure.eventhubs
  version: v1
  metadata:
    - name: connectionString
      value: ""
    - name: storageAccountName
      value: ""
    - name: storageAccountKey
      value: ""
    - name: storageContainerName
      value: ""

